import { Mppx, tempo } from 'mppx/nextjs';

/**
 * Shared MPP (Machine Payments Protocol) payment handler for swttr's paid,
 * agent-facing API surface (`/api/agent/*`).
 *
 * `MPP_SECRET_KEY` is self-generated by the seller (`openssl rand -base64 32`)
 * and signs the HTTP 402 payment challenges — it is NOT issued by Stripe/Tempo.
 * On testnet the `mppx` CLI auto-funds a caller wallet, so the full
 * 402 -> pay -> receipt loop can be exercised without any external account.
 *
 * For mainnet settlement, set `MPP_TESTNET=false` and provide a real
 * `MPP_RECIPIENT_ADDRESS` (the Tempo wallet that receives funds).
 */

const secretKey = process.env.MPP_SECRET_KEY;
if (!secretKey) {
  throw new Error(
    'MPP_SECRET_KEY is not set — generate one with `openssl rand -base64 32`',
  );
}

// pathUSD (TIP-20) on Tempo. Override with MPP_CURRENCY if needed.
const currency =
  process.env.MPP_CURRENCY ?? '0x20c0000000000000000000000000000000000000';

export const mppx = Mppx.create({
  secretKey,
  methods: [
    tempo({
      currency,
      recipient: process.env.MPP_RECIPIENT_ADDRESS as `0x${string}` | undefined,
      testnet: process.env.MPP_TESTNET !== 'false',
    }),
  ],
});
