import { NextResponse } from 'next/server';
import { Mppx, tempo } from 'mppx/nextjs';

/**
 * Shared MPP (Machine Payments Protocol) payment handler for swttr's paid,
 * agent-facing API surface (`/api/agent/*`).
 *
 * `MPP_SECRET_KEY` is self-generated by the seller (`openssl rand -base64 32`)
 * and signs the HTTP 402 payment challenges — it is NOT issued by Stripe/Tempo.
 * On testnet the `mppx` CLI auto-funds a caller wallet, so the full
 * 402 -> pay -> receipt loop can be exercised without any external account.
 *
 * For mainnet settlement, set `MPP_TESTNET=false` and provide a real
 * `MPP_RECIPIENT_ADDRESS` (the Tempo wallet that receives funds).
 */

const secretKey = process.env.MPP_SECRET_KEY;
if (!secretKey) {
  throw new Error(
    'MPP_SECRET_KEY is not set — generate one with `openssl rand -base64 32`',
  );
}

// pathUSD (TIP-20) on Tempo. Override with MPP_CURRENCY if needed.
const currency =
  process.env.MPP_CURRENCY ?? '0x20c0000000000000000000000000000000000000';

export const mppx = Mppx.create({
  secretKey,
  methods: [
    tempo({
      currency,
      recipient: process.env.MPP_RECIPIENT_ADDRESS as `0x${string}` | undefined,
      testnet: process.env.MPP_TESTNET !== 'false',
    }),
  ],
});

/**
 * Wrap a paid recommendation route with pre-charge validation.
 *
 * Bodies that would fail (or come back guaranteed-empty) in the v1 handler are
 * rejected with a 400 before the 402 challenge is ever issued, so agents don't
 * pay for a response they can't use:
 * - missing `weather.temperature` / `weather.wind_speed` (required by
 *   `validateRecommendationRequest`)
 * - `use_wardrobe_only: true` — wardrobes require a signed-in user, which the
 *   stateless agent API never has
 */
export function paidRecommendationRoute(
  amount: string,
  handler: (request: Request) => Promise<Response>,
): (request: Request) => Promise<Response> {
  const charged = mppx.charge({ amount })(handler);

  return async (request: Request) => {
    let body: Record<string, unknown> | null = null;
    try {
      body = await request.clone().json();
    } catch {
      body = null;
    }

    const weather = body?.weather as
      | { temperature?: unknown; wind_speed?: unknown }
      | undefined;
    if (!body || weather?.temperature === undefined || weather?.wind_speed === undefined) {
      return NextResponse.json(
        { error: 'weather.temperature and weather.wind_speed are required' },
        { status: 400 },
      );
    }

    if (body.use_wardrobe_only === true) {
      return NextResponse.json(
        {
          error:
            'use_wardrobe_only is not supported on the agent API — wardrobes require a signed-in user. Omit the flag to get catalog recommendations.',
        },
        { status: 400 },
      );
    }

    return charged(request);
  };
}
